kind: Deployment
apiVersion: apps/v1
metadata:
  name: nfs-client-provisioner
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: example.com/sit-nfs
            - name: NFS_SERVER
              value: <<SERVER_IP>>
            - name: NFS_PATH
              value: <<NFS_PATH>>
      volumes:
        - name: nfs-client-root
          nfs:
            server: <<SERVER_IP>>
            path: <<NFS_PATH>>
